In [1]:
import numpy as np

In [5]:
b = np.array([1,2,4,5])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_994226/4201870139.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  b = np.array([1,2,4,5][1,2])


TypeError: list indices must be integers or slices, not tuple

In [4]:
type(b)


numpy.ndarray

1.13 µs ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
l = range(1000000)

In [21]:
%timeit [i**2 for i in l]

162 ms ± 3.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
np_array = np.array(range(10))

In [23]:
%timeit np_array ** 2

2.29 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np_array.ndim

1

In [28]:
np_array.shape

(10,)

In [34]:
d = np.array([[1,2],[2,1],[1,1]])

In [32]:
d.ndim

2

In [35]:
d.shape

(3, 2)

In [37]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [42]:
l = np.arange(1,10,1.1)

In [43]:
print(l)

[1.  2.1 3.2 4.3 5.4 6.5 7.6 8.7 9.8]


### Data Conversion

In [45]:
c = np.array([1.5, 2, 3.5, 10])

In [47]:
print (c)

[ 1.5  2.   3.5 10. ]


In [48]:
c_int = np.array([1.5, 2, 3.5, 10], dtype = int)

In [49]:
print(c_int)

[ 1  2  3 10]
