In [2]:
import numpy as np

In [5]:
b = np.array([1,2,4,5])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_994226/4201870139.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  b = np.array([1,2,4,5][1,2])


TypeError: list indices must be integers or slices, not tuple

In [4]:
type(b)


numpy.ndarray

1.13 µs ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
l = range(1000000)

In [21]:
%timeit [i**2 for i in l]

162 ms ± 3.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
np_array = np.array(range(10))

In [23]:
%timeit np_array ** 2

2.29 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np_array.ndim

1

In [28]:
np_array.shape

(10,)

In [34]:
d = np.array([[1,2],[2,1],[1,1]])

In [32]:
d.ndim

2

In [35]:
d.shape

(3, 2)

In [37]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [42]:
l = np.arange(1,10,1.1)

In [43]:
print(l)

[1.  2.1 3.2 4.3 5.4 6.5 7.6 8.7 9.8]


----

# Data Conversion

In [45]:
c = np.array([1.5, 2, 3.5, 10])

In [47]:
print (c)

[ 1.5  2.   3.5 10. ]


In [52]:
c_int = np.array([1.5, 2, 3.5, 10], dtype = float)

In [49]:
print(c_int)

[ 1  2  3 10]


----

## int -> float --> str

----

# We can fetch multiple indices at once from an array.

## array [start , end , jump]

In [53]:
c_int[[1,2,0]]

array([2. , 3.5, 1.5])

In [56]:
c_int[:12:2]

array([1.5, 3.5])

In [57]:
c_int[2:] = 50

In [58]:
print(c_int)

[ 1.5  2.  50.  50. ]


In [59]:
print(c_int.reshape(2,2))

[[ 1.5  2. ]
 [50.  50. ]]


In [60]:
print(c_int)

[ 1.5  2.  50.  50. ]


In [61]:
n = c_int.reshape(2,2)
print(n)

[[ 1.5  2. ]
 [50.  50. ]]


In [62]:
print(n.reshape(4,))

[ 1.5  2.  50.  50. ]


In [63]:
print(n)

[[ 1.5  2. ]
 [50.  50. ]]


## If we don't know how many column then we can simply pass -1 . We just need to know how many rows we want to create.

In [67]:
n1 = c_int.reshape(1,-1)

In [65]:
print(n1)

[[ 1.5  2. ]
 [50.  50. ]]


In [68]:
print(c_int.T)

[ 1.5  2.  50.  50. ]


In [69]:
c_int.size

4

In [70]:
c_int.S

AttributeError: 'numpy.ndarray' object has no attribute 'S'

In [71]:
c_int[[2,3]]

array([50., 50.])

In [72]:
c_int[:]

array([ 1.5,  2. , 50. , 50. ])

----

In [78]:
a = np.array(range(16))

In [79]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [80]:
a[:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
b = a.reshape(4,-1)

In [91]:
print(b)
b[:1]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[0, 1, 2, 3]])

In [95]:
print(b[:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


![](./images/array.png)

In [96]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [98]:
b[:,:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

## array [row_start: row_end,      col_start_index : col_end_idx]
eg: a[ : , : 2 ]  --> all rows , col starts from beginning till idx 2

### a [ slice 1 , slice 2 ...] 
### a [ start,end,jump  , start,end,jump ...]

In [106]:
b[1:3 , 0:1]

array([[4],
       [8]])

In [110]:
b[: ,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [111]:
b>6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [112]:
b[b>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
a = np.arange(1,20)

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
d = np.loadtxt('survey.txt', dtype=int)

In [10]:
d

array([ 7, 10,  5, ...,  5,  9, 10])

In [12]:
d[:10]

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [19]:
negative = d[d<7]

In [20]:
negative

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [21]:
pos = d[d>7]

In [22]:
pos

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  8,  9,  9,
        9, 10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9,  8, 10,  8,  9, 10,
       10, 10,  9,  9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,
        9,  9,  9,  9,  8, 10,  8,  9,  9,  8,  8,  9, 10,  9, 10,  9,  9,
        8,  8,  9,  9,  9, 10, 10,  9, 10,  9,  9, 10,  9,  9, 10,  8,  9,
        9,  9,  9,  9,  8,  9,  9,  9,  9,  9,  8,  9, 10,  8,  9,  9,  9,
        9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9,  8,  8,  8, 10, 10,  9,
       10,  8, 10, 10,  8,  8, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,
        9, 10,  8,  9, 10,  9, 10, 10, 10,  9,  9, 10,  8, 10,  9,  9,  8,
        9,  9, 10,  8,  8,  9,  9,  9,  9, 10, 10,  9,  9,  9,  8, 10,  9,
        9,  9,  9,  9, 10,  9,  8,  9,  8,  9, 10,  9, 10, 10,  9,  9,  8,
        9,  9, 10,  9,  8, 10,  9,  9,  9,  9,  8, 10,  9, 10,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  8, 10, 10,  9,  9,  9, 10,  9, 10,
       10, 10, 10,  8, 10

In [36]:
ps = pos.size

In [37]:
ns = negative.size

In [38]:
ts = d.size

In [39]:
ps

712

In [33]:
score=100*(ps - ns)/ts

In [35]:
round(score,2)

32.56

In [69]:
watch = np.loadtxt('fit.txt', dtype='str')

In [70]:
watch

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [45]:
watch.ndim


2

In [46]:
watch.shape

(96, 6)

In [71]:
watch

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [62]:
wa
a = np.where(watch=='Active',True,False)

In [63]:
a

array(True)

In [59]:
b = np.arange(10)

In [60]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
watch[::,2]

In [83]:
date, step_count, mood, calorie, sleep, active = watch.T

In [139]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [90]:
active[active=='Active']
act = (active == 'Active')

In [91]:
act

array([False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False,  True, False,  True])

In [94]:
step_count[act]

array(['6915', '4732', '4550', '539', '6314', '614', '3149', '4005',
       '4880', '4136', '705', '570', '269', '493', '995', '1163', '6676',
       '3608', '774', '1421', '4064', '2725', '5934', '1867', '3721',
       '2909', '1648', '7102', '3941', '7422', '437', '1231', '4921',
       '221', '6500', '3575', '5537', '4108', '5376', '3066', '500',
       '2203'], dtype='<U10')

In [99]:
int_calorie = calorie[act].astype('int')

round(np.mean(int_calorie),2)

102.4

In [104]:
step_count[step_count > '5000']

array(['5464', '6041', '5461', '6915', '61', '539', '5464', '6041',
       '6314', '614', '705', '570', '5999', '6930', '5195', '546', '995',
       '6676', '774', '5934', '799', '7102', '7422', '6500', '651', '753',
       '518', '5537', '5376', '702'], dtype='<U10')

In [105]:
calorie > '150'

array([ True,  True, False,  True,  True, False, False,  True, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False,  True,  True, False,  True, False, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False, False,  True, False,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False, False, False, False])

In [111]:
int_step = step_count.astype('int')
int_cal = calorie.astype('int')


In [121]:
np.sum((int_step > 5000) & (int_cal > 150))

17

In [167]:
int_step > 5000

array([ True,  True, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [119]:
ans = np.sum((step_count>'5000') & (calorie>'150'))

In [120]:
ans

29

In [126]:
(np.sum((mood == 'Sad'))/mood.size)*100

30.208333333333332

In [131]:
import numpy as np

a = np.arange(5)

In [132]:
a

array([0, 1, 2, 3, 4])

In [136]:
b = [True, False, True, False]

In [137]:
b


[True, False, True, False]

In [138]:
a[b]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4

In [140]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [146]:
type(sleep)


numpy.ndarray

In [147]:
sleep.shape

(96,)

In [157]:
sleep.ndim
s =sleep.astype('int')

In [149]:
sleep <'6'

array([ True, False,  True,  True,  True, False, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
        True,  True, False, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True, False,  True,  True, False,  True, False,
        True, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True])

In [150]:
days = sleep[sleep<'6']

In [151]:
days

array(['5', '5', '4', '5', '5', '5', '5', '5', '4', '5', '5', '5', '5',
       '4', '5', '4', '5', '4', '3', '2', '5', '4', '5', '4', '5', '5',
       '5', '5', '5', '5', '5', '4', '3', '3', '4', '5', '5', '5', '3',
       '4', '4', '5', '5', '5', '5', '5', '5', '4', '3', '4', '5', '5',
       '4', '5', '3', '3', '3', '2', '3', '2', '5', '5', '5'],
      dtype='<U10')

In [152]:
days.size

63

In [156]:
np.max(step_count[sleep<'6'])

UFuncTypeError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('<U10'), dtype('<U10')) -> None

In [158]:
s<6

array([ True, False,  True,  True,  True, False, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
        True,  True, False, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True, False,  True,  True, False,  True, False,
        True, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True])

In [159]:
step = step_count.astype('int')

In [160]:
step

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [161]:
step[s]

array([4545,   61, 4545, 6915, 4545, 4340, 4340, 1230, 4545, 4340,   61,
       4545, 4340, 1230, 4545, 4340,   61, 4545, 6915, 4545, 4340,   61,
       4545, 4340, 4545,   61, 4545, 6915, 4545, 6915, 4545, 6915, 5461,
         25, 1258, 4545, 4340, 6915, 4545,   61, 6915, 4545, 4340, 4545,
       4340, 4545, 4340, 4545, 4340, 4545, 4340, 1230, 4340, 1230, 4340,
       4545, 4340, 1230,   61,   61, 1230,   61, 4545, 6915, 5461, 5461,
       6915, 4545, 4545, 4545, 5461, 6915, 6915, 4545, 4545, 4545, 4545,
       4545, 4545, 6915, 5461, 6915, 4545, 4545, 6915, 4545, 5461, 5461,
       5461,   25, 5461,   25,   61, 4545, 4545, 4545])

In [162]:
np.max(step[s])

6915

In [163]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [166]:
np.sort(np.unique(step_count))

array(['1163', '1230', '1231', '1258', '133', '1421', '1447', '153',
       '1580', '1648', '1696', '177', '181', '1831', '1867', '202',
       '2127', '2203', '2209', '221', '2255', '2374', '25', '2599', '269',
       '2725', '2822', '2909', '292', '299', '3066', '3148', '3149',
       '3158', '330', '3519', '3575', '36', '3608', '3721', '3881',
       '3941', '4005', '4033', '4037', '4061', '4064', '4068', '4108',
       '4136', '4275', '4340', '437', '4383', '4421', '4435', '4545',
       '4550', '4683', '4687', '4732', '4779', '4880', '4921', '493',
       '500', '518', '5195', '5376', '539', '546', '5461', '5464', '5537',
       '570', '5934', '5999', '6041', '61', '614', '6314', '6500', '651',
       '6676', '6915', '6930', '702', '705', '7102', '7422', '753', '774',
       '799', '995'], dtype='<U10')

In [170]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [171]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
a2 = a1.T

In [173]:
a2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [174]:
import pandas as pd

In [176]:
df = pd.read_csv('mckinsey.csv')

In [177]:
df

,country,year,population,continent,life_exp,gdp_cap
0,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,Afghanistan,1972,13079460,Asia,36.088,739.981106
...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623


In [178]:
df['year']

0       1952
1       1957
2       1962
3       1967
4       1972
        ... 
1699    1987
1700    1992
1701    1997
1702    2002
1703    2007
Name: year, Length: 1704, dtype: int64

In [180]:
type(df['year'])

pandas.core.series.Series

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [182]:
df.head?

Signature: df.head(n: 'int' = 5) -> 'Self'
Docstring:
Return the first `n` rows.

This function returns the first `n` rows for the object based
on position. It is useful for quickly testing if your object
has the right type of data in it.

For negative values of `n`, this function returns all rows except
the last `|n|` rows, equivalent to ``df[:n]``.

If n is larger than the number of rows, this function returns all rows.

Parameters
----------
n : int, default 5
    Number of rows to select.

Returns
-------
same type as caller
    The first `n` rows of the caller object.

See Also
--------
DataFrame.tail: Returns the last `n` rows.

Examples
--------
>>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
>>> df
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

Viewing the first 5 lines

>>> df.head()
      animal
0  

In [183]:
df

,country,year,population,continent,life_exp,gdp_cap
0,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,Afghanistan,1972,13079460,Asia,36.088,739.981106
...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623


In [184]:
df.reset_index()

,index,country,year,population,continent,life_exp,gdp_cap
0,0,Afghanistan,1952,8425333,Asia,28.801,779.445314
1,1,Afghanistan,1957,9240934,Asia,30.332,820.853030
2,2,Afghanistan,1962,10267083,Asia,31.997,853.100710
3,3,Afghanistan,1967,11537966,Asia,34.020,836.197138
4,4,Afghanistan,1972,13079460,Asia,36.088,739.981106
...,...,...,...,...,...,...,...
1699,1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306
1700,1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786
1701,1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960
1702,1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623


In [185]:
d = {'one':1,'two':2}

In [186]:
d


{'one': 1, 'two': 2}

In [187]:
d.type

AttributeError: 'dict' object has no attribute 'type'

In [188]:
type(d)

dict

In [190]:
d['one']

1

In [193]:
a = np.array([1,2,2,3,3,44,2])

In [194]:
a

array([ 1,  2,  2,  3,  3, 44,  2])