In [2]:
import numpy as np

In [5]:
b = np.array([1,2,4,5])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_994226/4201870139.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  b = np.array([1,2,4,5][1,2])


TypeError: list indices must be integers or slices, not tuple

In [4]:
type(b)


numpy.ndarray

1.13 µs ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
l = range(1000000)

In [21]:
%timeit [i**2 for i in l]

162 ms ± 3.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
np_array = np.array(range(10))

In [23]:
%timeit np_array ** 2

2.29 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np_array.ndim

1

In [28]:
np_array.shape

(10,)

In [34]:
d = np.array([[1,2],[2,1],[1,1]])

In [32]:
d.ndim

2

In [35]:
d.shape

(3, 2)

In [37]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [42]:
l = np.arange(1,10,1.1)

In [43]:
print(l)

[1.  2.1 3.2 4.3 5.4 6.5 7.6 8.7 9.8]


----

# Data Conversion

In [45]:
c = np.array([1.5, 2, 3.5, 10])

In [47]:
print (c)

[ 1.5  2.   3.5 10. ]


In [52]:
c_int = np.array([1.5, 2, 3.5, 10], dtype = float)

In [49]:
print(c_int)

[ 1  2  3 10]


----

## int -> float --> str

----

# We can fetch multiple indices at once from an array.

## array [start , end , jump]

In [53]:
c_int[[1,2,0]]

array([2. , 3.5, 1.5])

In [56]:
c_int[:12:2]

array([1.5, 3.5])

In [57]:
c_int[2:] = 50

In [58]:
print(c_int)

[ 1.5  2.  50.  50. ]


In [59]:
print(c_int.reshape(2,2))

[[ 1.5  2. ]
 [50.  50. ]]


In [60]:
print(c_int)

[ 1.5  2.  50.  50. ]


In [61]:
n = c_int.reshape(2,2)
print(n)

[[ 1.5  2. ]
 [50.  50. ]]


In [62]:
print(n.reshape(4,))

[ 1.5  2.  50.  50. ]


In [63]:
print(n)

[[ 1.5  2. ]
 [50.  50. ]]


## If we don't know how many column then we can simply pass -1 . We just need to know how many rows we want to create.

In [67]:
n1 = c_int.reshape(1,-1)

In [65]:
print(n1)

[[ 1.5  2. ]
 [50.  50. ]]


In [68]:
print(c_int.T)

[ 1.5  2.  50.  50. ]


In [69]:
c_int.size

4

In [70]:
c_int.S

AttributeError: 'numpy.ndarray' object has no attribute 'S'

In [71]:
c_int[[2,3]]

array([50., 50.])

In [72]:
c_int[:]

array([ 1.5,  2. , 50. , 50. ])

----

In [78]:
a = np.array(range(16))

In [79]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [80]:
a[:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
b = a.reshape(4,-1)

In [91]:
print(b)
b[:1]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[0, 1, 2, 3]])

In [95]:
print(b[:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


![](./images/array.png)

In [96]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [98]:
b[:,:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

## array [row_start: row_end,      col_start_index : col_end_idx]
eg: a[ : , : 2 ]  --> all rows , col starts from beginning till idx 2

### a [ slice 1 , slice 2 ...] 
### a [ start,end,jump  , start,end,jump ...]

In [106]:
b[1:3 , 0:1]

array([[4],
       [8]])

In [110]:
b[: ,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [111]:
b>6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [112]:
b[b>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
a = np.arange(1,20)

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
d = np.loadtxt('survey.txt', dtype=int)

In [10]:
d

array([ 7, 10,  5, ...,  5,  9, 10])

In [12]:
d[:10]

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [19]:
negative = d[d<7]

In [20]:
negative

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [21]:
pos = d[d>7]

In [22]:
pos

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  8,  9,  9,
        9, 10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9,  8, 10,  8,  9, 10,
       10, 10,  9,  9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,
        9,  9,  9,  9,  8, 10,  8,  9,  9,  8,  8,  9, 10,  9, 10,  9,  9,
        8,  8,  9,  9,  9, 10, 10,  9, 10,  9,  9, 10,  9,  9, 10,  8,  9,
        9,  9,  9,  9,  8,  9,  9,  9,  9,  9,  8,  9, 10,  8,  9,  9,  9,
        9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9,  8,  8,  8, 10, 10,  9,
       10,  8, 10, 10,  8,  8, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,
        9, 10,  8,  9, 10,  9, 10, 10, 10,  9,  9, 10,  8, 10,  9,  9,  8,
        9,  9, 10,  8,  8,  9,  9,  9,  9, 10, 10,  9,  9,  9,  8, 10,  9,
        9,  9,  9,  9, 10,  9,  8,  9,  8,  9, 10,  9, 10, 10,  9,  9,  8,
        9,  9, 10,  9,  8, 10,  9,  9,  9,  9,  8, 10,  9, 10,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  8, 10, 10,  9,  9,  9, 10,  9, 10,
       10, 10, 10,  8, 10

In [36]:
ps = pos.size

In [37]:
ns = negative.size

In [38]:
ts = d.size

In [39]:
ps

712

In [33]:
score=100*(ps - ns)/ts

In [35]:
round(score,2)

32.56

In [69]:
watch = np.loadtxt('fit.txt', dtype='str')

In [70]:
watch

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [45]:
watch.ndim


2

In [46]:
watch.shape

(96, 6)

In [71]:
watch

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [62]:
wa
a = np.where(watch=='Active',True,False)

In [63]:
a

array(True)

In [59]:
b = np.arange(10)

In [60]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
watch[::,2]

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [83]:
date, step_count, mood, calorie, sleep, active = watch.T

In [85]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [90]:
active[active=='Active']
act = (active == 'Active')

In [91]:
act

array([False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False,  True, False,  True])

In [94]:
step_count[act]

array(['6915', '4732', '4550', '539', '6314', '614', '3149', '4005',
       '4880', '4136', '705', '570', '269', '493', '995', '1163', '6676',
       '3608', '774', '1421', '4064', '2725', '5934', '1867', '3721',
       '2909', '1648', '7102', '3941', '7422', '437', '1231', '4921',
       '221', '6500', '3575', '5537', '4108', '5376', '3066', '500',
       '2203'], dtype='<U10')

In [99]:
int_calorie = calorie[act].astype('int')

round(np.mean(int_calorie),2)

102.4

In [104]:
step_count[step_count > '5000']

array(['5464', '6041', '5461', '6915', '61', '539', '5464', '6041',
       '6314', '614', '705', '570', '5999', '6930', '5195', '546', '995',
       '6676', '774', '5934', '799', '7102', '7422', '6500', '651', '753',
       '518', '5537', '5376', '702'], dtype='<U10')

In [105]:
calorie > '150'

array([ True,  True, False,  True,  True, False, False,  True, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False,  True,  True, False,  True, False, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False, False,  True, False,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False, False, False, False])

In [ ]:
step_coun


In [110]:
step_count > '5000' & calorie > '150'

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''